%YAML:1.0

#---------------------------------
#hd data preprocess config file
#---------------------------------

HdCamFx: 1204.100702372
HdCamFy: 1210.073064003
HdCamCx: 731.315716622
HdCamCy: 548.808242006
HdCamk1: -0.091441807
HdCamk2: 0.088316997
HdCamk3: 0.0
HdCamp1: 0.000245020
HdCamp2: -0.000004751

ImgPath: "/Users/TLG/Downloads/data/hd/image"
PosPath: "/Users/TLG/Downloads/data/hd/camera.txt"
OutPath: "/Users/TLG/Downloads/data/hd/result/"

ImgWd:  1440
ImgHg:  1080
ImgFps: 20  #0 every frame is keyframe
ImgRgb: 1  #rgb 1  rbg 0 

StNo: 550 #2160     #550
EdNo: 650 #2165     #600 

ExtriPath: "/Users/TLG/Downloads/data/weiya/20191105/extrinsics.xml"
BsPath:    "/Users/TLG/Downloads/data/weiya/20191105/BS_0001_20191105.bs"

#vocabulary path 
VocPath: "/Users/TLG/Documents/Positioning/Vocabulary/ORBvoc.txt"

#feature params
FeatureCnt:   2000  #特征点提取数量
PyramidLevel: 8     #图片金字塔层数
ScaleFactor:  1.3   #图片金字塔缩小比
SearchRadius: 20    #视觉匹配搜索范围
MatchRatio:   0.4   #匹配比例(比例越大,匹配要求越低,匹配点越多)


#Visualization
ViewEnable: 1
ViewerW:    1080
ViewerH:    768
ViewptX:    0
ViewptY:    -10
ViewptZ:    -0.1
ViewptF:    800

