%YAML:1.0

#---------------------------------
#weiya data preprocess config file
#---------------------------------


#util info
StNo: 0
EdNo: 5

#camera param
ImgWd: 1080
ImgHg: 720

#path 
ImgPath: "/Users/TLG/Downloads/data/weiya/20191105/gray"
PosPath: "/Users/TLG/Downloads/data/weiya/20191105/gray/pst.txt"
OutPath: "/Users/TLG/Downloads/data/weiya/20191105/result/"

ExtriPath: "/Users/TLG/Downloads/data/weiya/extrinsics.xml"
BsPath:    "/Users/TLG/Downloads/data/weiya/BS_0001_20191105.bs"


#feature params
FeatureCnt:   3000
PyramidLevel: 8
ScaleFactor:  1.2
SearchScale:  500
