%YAML:1.0

#---------------------------------
#weiya data preprocess config file
#---------------------------------


#util info
StNo: 680
EdNo: 700 #800

#camera param
ImgWd:  4096
ImgHg:  2168
ImgFps: 0  #0 every frame is keyframe
ImgRgb: 1  #rgb 1  rbg 0 

#path 
ImgPath: "/Users/TLG/Downloads/data/weiya/20191105/gray"
PosPath: "/Users/TLG/Downloads/data/weiya/20191105/gray/pst.txt"
OutPath: "/Users/TLG/Downloads/data/weiya/20191105/result/"

ExtriPath: "/Users/TLG/Downloads/data/weiya/20191105/extrinsics.xml"
BsPath:    "/Users/TLG/Downloads/data/weiya/20191105/BS_0001_20191105.bs"

#vocabulary path 
VocPath: "/Users/TLG/Documents/Positioning/Vocabulary/ORBvoc.txt"

#feature params
FeatureCnt:   3000
PyramidLevel: 8
ScaleFactor:  1.3
SearchScale:  500


#Visualization
ViewEnable: 1
ViewerW:    1080
ViewerH:    768
ViewptX:    0
ViewptY:    -10
ViewptZ:    -0.1
ViewptF:    800

