%YAML:1.0

#---------------------------------
#weiya data preprocess config file
#---------------------------------


#util info
StNo: 850
EdNo: 950 #800

#camera param
ImgWd:  4096
ImgHg:  2168
ImgFps: 0  #0 every frame is keyframe
ImgRgb: 1  #rgb 1  rbg 0 

#path 
ImgPath: "/media/tu/Work/Datas/1002-0001-191107-00/gray"
SemPath: ""
PosPath: "/media/tu/Work/Datas/1002-0001-191107-00/gray/pst.txt"
OutPath: "/media/tu/Work/Datas/1002-0001-191107-00/Result"

ExtriPath: "/media/tu/Work/Datas/1002-0001-191107-00/Params/extrinsics.xml"
BsPath:    "/media/tu/Work/Datas/1002-0001-191107-00/Params/BS_0001_20191105.bs"

#feature params
FeatureCnt:   2000  #特征点提取数量
PyramidLevel: 8     #图片金字塔层数
ScaleFactor:  1.3   #图片金字塔缩小比
SearchRadius:  500   #视觉匹配搜索范围
MatchRatio:   0.8   #匹配比例(比例越大,匹配要求越低,匹配点越多)


#Visualization
ViewEnable: 1
ViewerW:    1080
ViewerH:    768
ViewptX:    0
ViewptY:    -10
ViewptZ:    -0.1
ViewptF:    800

#ISerialization
MapSave: 1