%YAML:1.0

#---------------------------------
#weiya data preprocess config file
#---------------------------------


#util info
#StNo: 680
#EdNo: 685

#camera param
ImgWd:  4096
ImgHg:  2168
ImgFps: 10  #0 every frame is keyframe


#path 
#PrjPath: "/media/tlg/work/tlgfiles/WEIYA/9900000120042200/"

LogPath: ""
LogPrio: "DEBUG"  #log打印等级 DEBUG INFO WARNNING ERROR CRITICAL
#ImgPath: ""
#SemPath: ""
#PosPath: "/Users/TLG/Downloads/data/weiya/20191105/gray/pst.txt"
#OutPath: "/Users/TLG/Downloads/data/weiya/20191105/result/"

#CamMatrixPath: "/media/tlg/work/tlgfiles/WEIYA/9900000120042200/config/extrinsics.xml"
#BsPath:        "/media/tlg/work/tlgfiles/WEIYA/9900000120042200/config/BS_0001_20191105.bs"

#feature params
FeatureCnt:   2000  #特征点提取数量
PyramidLevel: 8     #图片金字塔层数
ScaleFactor:  1.3   #图片金字塔缩小比
SearchRadius: 300   #视觉匹配搜索范围



#set Mask
MaskEnable: 0

#Visualization
ViewEnable: 0

#ISerialization
MapSave: 0