%YAML:1.0

#---------------------------------
#weiya data preprocess config file
#---------------------------------


#util info
StNo: 680
EdNo: 685 #800

#camera param
ImgWd:  4096
ImgHg:  2168
ImgFps: 0  #0 every frame is keyframe
ImgRgb: 1  #rgb 1  rbg 0 

#path 
ImgPath: "/Users/TLG/Downloads/data/weiya/20191105/gray"
SemPath: ""
PosPath: "/Users/TLG/Downloads/data/weiya/20191105/gray/pst.txt"
OutPath: "/Users/TLG/Downloads/data/weiya/20191105/result/"

ExtriPath: "/Users/TLG/Downloads/data/weiya/20191105/extrinsics.xml"
BsPath:    "/Users/TLG/Downloads/data/weiya/20191105/BS_0001_20191105.bs"

#vocabulary path 
VocPath: "/Users/TLG/Documents/Positioning/Vocabulary/ORBvoc.txt"

#feature params
FeatureCnt:   2000  #特征点提取数量
PyramidLevel: 8     #图片金字塔层数
ScaleFactor:  1.3   #图片金字塔缩小比
SearchRadius:  20   #视觉匹配搜索范围
MatchRatio:   0.8   #匹配比例(比例越大,匹配要求越低,匹配点越多)


#Visualization
ViewEnable: 1
ViewerW:    1080
ViewerH:    768
ViewptX:    0
ViewptY:    -10
ViewptZ:    -0.1
ViewptF:    800

#ISerialization
MapSave: 1